spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loginProject
    username: root
    password: tkfkdtkfkd^6
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080


